{% set version = "1.30.1" %}
{% set build = 1 %}

package:
  name: solara
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/s/solara/solara-{{ version }}.tar.gz
    sha256: 86ca619ce2e5209ebe0bda9f6f13036eac045dfea2a5f11def336f51e93d136f
    folder: solara
  - url: https://pypi.io/packages/source/s/solara_assets/solara_assets-{{ version }}.tar.gz
    sha256: 2aa3b6c9fae3a9843be06820f4d5cbe78bd681f5173a70dcb2d0872abbc5735a
    folder: solara_assets

build:
  noarch: python
  number: {{ build }}


outputs:
  - name: solara
    version: {{ version }}
    build:
      noarch: python
      script: |
        set -euxo pipefail
        cd solara
        python -m pip install -vv --no-deps .
      entry_points:
        - solara = solara.__main__:main
    requirements:
      host:
        - python >=3.8
        - hatchling
        - pip
      run:
        - python >=3.8
        - reacton >=1.7.1
        - ipywidgets
        - cachetools
        - filelock
        - markdown
        - pymdown-extensions
        - humanize
        - ipyvuetify >=1.8.10
        - ipyvue >=1.9.0
        - jinja2
        - markupsafe
        - click >=7.1.0
        - rich-click
        - uvicorn
        - websockets
        - starlette
        - jupyter_client >=7.0.0
        - watchdog
        - requests
        - nbformat
        - ipykernel
        - watchfiles
      run_constrained:
        # Can't use {{ pin_subpackage("solara-assets", exact=True) }}
        # as the hashes are different
        # TODO: revisit after https://github.com/conda/conda-build/issues/4415
        - solara-assets ={{ version }}=*_{{ build }}
    test:
      imports:
        - solara
      commands:
        - pip check
        - solara --help
      requires:
        - pip

  - name: solara-assets
    version: {{ version }}
    build:
      noarch: python
      script: |
        set -euxo pipefail
        cd solara_assets
        python -m pip install -vv --no-deps .
    requirements:
      host:
        - python
        - hatchling >=0.25
        - pip
      run:
        - python
        - solara
    test:
      imports:
        - solara_assets
      commands:
        - pip check
      requires:
        - pip
    about:
      license: MIT AND BSD-3-Clause AND Apache-2.0
      license_file:
        - solara_assets/LICENSE
        - solara_assets/cdn/codemirror@5.65.3/LICENSE
        - solara_assets/cdn/@widgetti/vue-grid-layout@2.3.13-alpha.2/LICENSE
        - solara_assets/cdn/vega-lite@5.2.0/LICENSE
        - solara_assets/cdn/vega@5.21.0/LICENSE
        - solara_assets/cdn/mermaid@10.8.0/LICENSE
        - solara_assets/cdn/echarts@5.4.0/LICENSE
        - solara_assets/cdn/echarts@5.4.0/NOTICE
        - solara_assets/cdn/echarts@5.4.0/licenses/LICENSE-d3
        - solara_assets/cdn/vega-embed@6.20.2/LICENSE


about:
  home: https://github.com/widgetti/solara
  summary: 'A Pure Python, React-style Framework for Scaling Your Jupyter and Web Apps'
  license: MIT AND BSD-3-Clause
  license_file:
    - solara/LICENSE
#    - solara/packages/solara-widget-manager/LICENSE.voila.txt


extra:
  recipe-maintainers:
    - maartenbreddels
    - mariobuikhuizen
    - dhirschfeld
    - iisakkirotko
