{% set version = "1.48.0" %}
{% set build = 0 %}

package:
  name: solara-suite
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/s/solara/solara-{{ version }}.tar.gz
    sha256: 13bfe8f31293c81308e6c4405e8c04c0614ee27679ffb289647689d97cf29291
    folder: solara
  - url: https://pypi.org/packages/source/s/solara-ui/solara_ui-{{ version }}.tar.gz
    sha256: 2bb3a6d976573e7e547f6e64f565e39e0d2911f69ddae186a44bad92df745fa9
    folder: solara_ui
  - url: https://pypi.org/packages/source/s/solara-server/solara_server-{{ version }}.tar.gz
    sha256: 9918bf8bae61ee03817fbe350d463ea87bd5240c90006380457a768b6e4c9990
    folder: solara_server
  - url: https://pypi.org/packages/source/s/solara_assets/solara_assets-{{ version }}.tar.gz
    sha256: af5f7d916689a926d6745760a3d695e7eb0ec7275341650be7c0a901d1caa6c9
    folder: solara_assets

build:
  noarch: python
  number: {{ build }}


outputs:
  - name: solara
    version: {{ version }}
    build:
      noarch: python
      script: |
        set -euxo pipefail
        cd solara
        python -m pip install -vv --no-deps .
    requirements:
      host:
        - python {{ python_min }}
        - hatchling
        - pip
      run:
        - python >={{ python_min }}
        - solara-ui
        - solara-server
      run_constrained:
        # Can't use {{ pin_subpackage("solara-assets", exact=True) }}
        # as the hashes are different
        # TODO: revisit after https://github.com/conda-forge/staged-recipes/issues/23382
        - solara-assets ={{ version }}=*_{{ build }}
        - solara-server ={{ version }}=*_{{ build }}
        - solara-ui ={{ version }}=*_{{ build }}

    test:
      imports:
        - solara
      commands:
        - pip check
        - solara --help
      requires:
        - pip

  - name: solara-ui
    version: {{ version }}
    build:
      noarch: python
      script: |
        set -euxo pipefail
        cd solara_ui
        python -m pip install -vv --no-deps .
    requirements:
      host:
        - python {{ python_min }}
        - hatchling >=0.25
        - pip
      run:
        - python >={{ python_min }}
        - reacton >=1.9.0
        - ipywidgets >=7.7
        - ipyvuetify >=1.6.10
        - ipyvue >=1.9.0
        - requests
        - humanize
        # solara-ui optional dependencies follow
        - markdown
        - pymdown-extensions
        - pygments
        - cachetools
        - numpy
        - pillow

    test:
      imports:
        - solara
      commands:
        - pip check
      requires:
        - pip

  - name: solara-server
    version: {{ version }}
    build:
      noarch: python
      script: |
        set -euxo pipefail
        cd solara_server
        python -m pip install -vv --no-deps .
      entry_points:
        - solara = solara.__main__:main
    requirements:
      host:
        - python {{ python_min }}
        - hatchling >=0.25
        - pip
      run:
        - python >={{ python_min }}
        - jinja2
        - click >=7.1.0
        - rich-click
        - filelock
        - ipykernel
        - nbformat
        - jupyter_client >=7.0.0
        - solara-ui
        # solara-server optional dependencies follow
        - uvicorn
        - websockets
        - starlette
        - watchfiles
        - watchdog
      run_constrained:
        # Can't use {{ pin_subpackage("solara-assets", exact=True) }}
        # as the hashes are different
        # TODO: revisit after https://github.com/conda/conda-build/issues/4415
        - solara-assets ={{ version }}=*_{{ build }}
    test:
      imports:
        - solara
      commands:
        - pip check
        - solara --help
      requires:
        - pip

  - name: solara-assets
    version: {{ version }}
    build:
      noarch: python
      script: |
        set -euxo pipefail
        cd solara_assets
        python -m pip install -vv --no-deps .
    requirements:
      host:
        - python {{ python_min }}
        - hatchling >=0.25
        - pip
      run:
        - python >={{ python_min }}
        - solara

    test:
      imports:
        - solara_assets
      # pip check fails, see https://github.com/conda-forge/solara-feedstock/pull/24#issuecomment-2072211293
      # And https://github.com/pypa/pip/pull/11159
      # commands:
      #   - pip check
      requires:
        - pip
        - python {{ python_min }}
    about:
      license: MIT AND BSD-3-Clause AND Apache-2.0
      license_file:
        - solara_assets/LICENSE
        - solara_assets/cdn/codemirror@5.65.3/LICENSE
        - solara_assets/cdn/@widgetti/vue-grid-layout@2.3.13-alpha.2/LICENSE
        - solara_assets/cdn/vega-lite@5.2.0/LICENSE
        - solara_assets/cdn/vega@5.21.0/LICENSE
        - solara_assets/cdn/mermaid@10.8.0/LICENSE
        - solara_assets/cdn/echarts@5.4.0/LICENSE
        - solara_assets/cdn/echarts@5.4.0/NOTICE
        - solara_assets/cdn/echarts@5.4.0/licenses/LICENSE-d3
        - solara_assets/cdn/vega-embed@6.20.2/LICENSE


about:
  home: https://github.com/widgetti/solara
  summary: 'A Pure Python, React-style Framework for Scaling Your Jupyter and Web Apps'
  license: MIT AND BSD-3-Clause
  license_file:
    - solara/LICENSE
#    - solara/packages/solara-widget-manager/LICENSE.voila.txt


extra:
  feedstock-name: solara
  recipe-maintainers:
    - maartenbreddels
    - mariobuikhuizen
    - dhirschfeld
    - iisakkirotko
